nodejs:
  applicationPort: 4000
  memoryRequests: "512Mi"
  cpuRequests: "100m"
  memoryLimits: "1024Mi"
  cpuLimits: "500m"
  environment:
    PUBLIC_PROTOCOL: https
    REFORM_TEAM: pcq
    REFORM_SERVICE_NAME: pcq-frontend
    S2S_URL:
    VALIDATION_SERVICE_URL:
    SUBMIT_SERVICE_URL:
    ORCHESTRATION_SERVICE_URL: http://pcq-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    REFORM_ENVIRONMENT: '{{ .Values.global.environment }}'
  image: hmctspublic.azurecr.io/pcq/frontend:latest
  ingressHost: pcq.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: pcq

  keyVaults:
    pcq:
      resourceGroup: pcq
      secrets:
        - AppInsightsInstrumentationKey
        - jwt-secret

redis:
  enabled: false
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
