nodejs:
  environment:
    REDIS_HOST: ${SERVICE_NAME}-redis-master
    REDIS_PORT: 6379
    REDIS_USE_TLS: false
    JWT_SECRET: ${JWT_SECRET}
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

redis:
  enabled: true
