
nodejs:
  memoryRequests: "512Mi"
  cpuRequests: "100m"
  memoryLimits: "1024Mi"
  cpuLimits: "500m"
  applicationPort: 3000
  memoryRequests: "512Mi"
  cpuRequests: "100m"
  memoryLimits: "1024Mi"
  cpuLimits: "500m"
  environment:
    PUBLIC_PROTOCOL: https
    REFORM_TEAM: pcq
    REFORM_SERVICE_NAME: pcq-frontend
    S2S_URL:
    VALIDATION_SERVICE_URL:
    SUBMIT_SERVICE_URL:
    ORCHESTRATOR_SERVICE_URL:
    REFORM_ENVIRONMENT: aat
    USE_REDIS: true
    REDIS_USE_TLS: false
    USE_IDAM: false
    REQUIRE_CCD_CASE_ID: true
  image: hmctspublic.azurecr.io/pcq/pcq-frontend:latest
  aadIdentityName: pcq

redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
