appName: 'frontend'
project: 'pcq'
environment: 'laptop'
version: 'x.x-laptop'
deployment_env: 'local'
showSitemap: false

service:
  name: 'pcq-frontend'

e2e:
  frontendUrl: 'https://pcq-frontend-staging.service.core-compute-aat.internal'
  proxyServer: ''
  proxyBypassList: ''
  outputDirectory: './functional-output'
  defaultEnvironmentNodeEnv: 'development'
  waitForTimeoutValue: 5000
  waitForActionValue: 100
  runBasicTests: false

saucelabs:
  browser: 'chrome'
  username: 'salivendra'
  key: 'd8c2d5fc-1807-434d-bdbd-133e326416ec'
  tunnelId: 'reformtunnel'
  waitForTimeout: 5000
  smartWait: 5000

